### ISSUE TITLE
cifs/sbm3.1.1 with multichannel feature on Ubuntu 20.10

### ISSUE THREAD

**Issue by ipvirg** [cifsd-team/cifsd#519]
Need guidance on configuring Ubuntu 20 client mounting CIFS/smb3.1.1 with multichannel

<netapp storage server with cifs/smb3.1.1 multilchannel enabled><-----><Ubuntu 20.10 client mounting cifs smb3.1.1>

The following config line in samba appeared to be the Linux client as a samba server 
/etc/samba/smb.conf
server multi channel support = yes

What I need is to configure the Linux client an SMB3 client that discovers the multichannel feature from the storage server
i.e. when i monitor the cifs session in the Linux client via "netstat -an | grep 445" command, should see multiple tcp sessions for cifs/smb port 445. In windows world, we can see the multichannel sessions configurable to 4, 8, and 16 tcp sessions and can be set using powershell command Set-SmbClientConfiguration. Tried to explore smbclient command but have not found equivalent to set multichannel as Set-SmbClientConfiguration does.

**Comment by mmakassikis** [comment]
This is the wrong project to ask this.

cifsd is a server side implemention of SMB (which does not currently implement multichannel).
Enabling multi channel on a Samba server won't help, since that's a server option.

A quick google search suggests the Linux kernel CIFS client implements multichannel, though you will need a rather recent kernel (5.5+), and most likely an up to date cifs-utils package for the mount.cifs tool.

**Comment by ipvirg** [comment]
Thanks for the response @mmakassikis. I do have kernel 5.8, cifs-utils package installed and no issues with mount.cifs, but still don't see the multichannel sessions. Will close this thread for now.

**Comment by namjaejeon** [comment]
@mmakassikis Right, thanks for your answer!
@ipvirg I am preparing smb3 multichannel feature in cifsd(ksmbd). I hope it will be done soon. If it is complete, I will share it with you. You can try that(cifs & cifsd) instead of samba & cifs.

**Comment by ipvirg** [comment]
@namjaejeon thank you. Looking forward to use it once available.
